version: '3'
services:
  mongodb:
    image: mongo:4.4
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db:rw

volumes:
  mongodb_data:
