version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    stdin_open: true
    ports:
      - 3000:3000
    restart: always
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    extends:
      file: docker-compose.yml
      service: mongodb

volumes:
  mongodb_data:
